version: "2.4"
services:
 Eureka:
  build: .\EurekaServer
  ports:
   - "8761:8761"
  image: "eureka"
 
 Zuul:
  build: .\zuul-gateway
  ports:
   - "8093:8093"
  image: "zuul" 
  depends_on: 
  - Eureka
  environment:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://Eureka:8761/eureka  

 mysqldb:
  image: mysql:5.7
  restart: unless-stopped
  environment:
   - MYSQL_ROOT_PASSWORD=rootpass
   - MYSQL_DATABASE=restaurant      
   - MYSQL_USER=sisou
   - MYSQL_PASSWORD=sisou
  ports:
   - "3306:3306"
  volumes:
   - .m2:/root/.m2
  stdin_open: true
  tty: true


 livraison-A:
  build: .\LivraisonMS
  image: livraison
  ports:
    - 8083:8083
  depends_on:
   - Eureka
  environment:
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://Eureka:8761/eureka   
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/restaurant?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "sisou",
        "spring.datasource.password" : "sisou",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
      
 MSCommande-A:
  build: .\MSCommande
  image: commande
  ports:
    - 8085:8085
  depends_on:
   - Eureka
  environment:
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://Eureka:8761/eureka   
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/restaurant?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "sisou",
        "spring.datasource.password" : "sisou",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

 RestaurantMS-A:
  build: .\RestaurantMS
  image: restaurant
  ports:
    - 8090:8090
  depends_on:
   - Eureka
  environment:
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://Eureka:8761/eureka   
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/restaurant?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "sisou",
        "spring.datasource.password" : "sisou",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

 PlatMS-A:
  build: .\PlatMS
  image: plat
  ports:
    - 8082:8082
  depends_on:
   - Eureka
  environment:
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://Eureka:8761/eureka   
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/restaurant?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "sisou",
        "spring.datasource.password" : "sisou",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
 

volumes:
  db:
     
